#KioskURL=https://docs.google.com/presentation/d/1cUJkZT8T8xVz6g9N_PrCgHIF7wcKQy1bIRtCutK9z5E/present?start=true&loop=true&delayms=5000
KioskURL=http://localhost/
RefreshTime=30
CacheInterval=2
#StartTime=08:00
#StopTime=18:00
