# ==========================================
# Kiosk configuratiebestand
# ==========================================

# Runtime doel
KioskURL=https://docs.google.com/presentation/d/1cUJkZT8T8xVz6g9N_PrCgHIF7wcKQy1bIRtCutK9z5E/present?start=false&loop=false&delayms=60000
KioskMode=presentation
SelectedPresetUrl=https://docs.google.com/presentation/d/1cUJkZT8T8xVz6g9N_PrCgHIF7wcKQy1bIRtCutK9z5E/edit?slide=id.g3a9ff8495d4_1_12#slide=id.g3a9ff8495d4_1_12
SequenceKey=
ResolvedPresetUrl=https://docs.google.com/presentation/d/1cUJkZT8T8xVz6g9N_PrCgHIF7wcKQy1bIRtCutK9z5E/edit?slide=id.g3a9ff8495d4_1_12#slide=id.g3a9ff8495d4_1_12
SequenceData=
Timezone=Europe/Brussels

# Google Slides opties
SlideStart=false
SlideLoop=false
SlideDelay=60000

# Refresh instellingen
RefreshTime=60
CacheInterval=2

# Tijdschema (optioneel)
#StartTime=08:00
#StopTime=18:00
